# Automatically close issues if the body doesn't match our regular expression

name: Enforce issue template

# Run when a new issue is created
# roots/issue-closer action doesn't support other types
on:
  issues:
    types: [opened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce issue template
        uses: roots/issue-closer@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: >
            Hello @${issue.user.login} :wave:! Thanks a lot for reporting an
            issue after finding a bug in Kurento.


            However, we cannot accept your report and it is being automatically
            closed, because **it doesn't follow the issue template**.


            We need all reports to follow the template, because it helps us to
            understand and categorize issues. Please, create a new issue and
            follow the template, or reopen this same issue to edit and provide
            all required information.
          issue-pattern: /Describe.*Reproduce/gs
