# Workflow syntax for GitHub Actions:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

# Run some verification and organizative work on each newly opened issue.
name: New-Issue

# Run only when a new issue is opened.
# (roots/issue-closer action doesn't support other event types)
on:
  issues:
    types: [opened]

jobs:
  # Close the issue if its body doesn't match a regular expression.
  check-template:
    name: Check Template
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/issue-auto-closer
      - name: Issue auto-closer
        uses: roots/issue-closer-action@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-pattern: '\[[xX]\] I agree to fill this issue template'
          issue-close-message: >
            Hello @${issue.user.login} :wave:! Thanks a lot for reporting an
            issue after finding a bug.


            However, **your report doesn't follow the [issue template](https://github.com/j1elo/test-repo/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)**,
            so it is being automatically closed. We are really sorry for that,
            but we need all reports to follow the template, or else it won't be
            possible to understand and help with all issues.


            Please, create a new issue following the template, or reopen this
            same issue to edit and provide all required information.

  # Add the issue to the "Triage" Project Board.
  add-to-project:
    name: Add to Project
    runs-on: ubuntu-latest

    # Wait for previous job to finish (disable parallel run).
    needs: check-template

    steps:
      # https://github.com/marketplace/actions/github-api-request
      - id: get-issue
        name: Get Issue Data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/issues/:issue_number
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/github-project-automation
      - name: GitHub Project Automation+
        uses: alex-page/github-project-automation-plus@v0.3.0
        # Run only if "check-template" didn't close the issue.
        if: ${{ fromJson(steps.get-issue.outputs.data).state == 'open' }}
        with:
          repo-token: ${{ secrets.NEW_ISSUE_TOKEN }}
          project: projectABCDE
          column: Backlog Candidates
